### List All Orders
GET https://localhost:8080/brokage/api/admin/orders
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### List Orders by Customer ID
GET https://localhost:8080/brokage/api/admin/orders?customerId=1
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Get Specific Order
GET https://localhost:8080/brokage/api/admin/orders/9
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Match Specific Order
POST https://localhost:8080/brokage/api/admin/orders/9/match
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Place Order
POST https://localhost:8080/brokage/api/admin/orders/
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "customerId": 1,
  "assetName": "USD",
  "side": "BUY",
  "size": 2,
  "price": 34.10
}

### Match Order
POST https://localhost:8080/brokage/api/admin/orders/1/match
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Get Order
GET https://localhost:8080/brokage/api/admin/orders/1
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Delete Order
DELETE https://localhost:8080/brokage/api/admin/orders/2
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
