### Get orders
GET https://localhost:8080/brokage/api/admin/orders
Accept:application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Get orders
GET https://localhost:8080/brokage/api/admin/orders?customerId=1
Accept:application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Get orders
GET https://localhost:8080/brokage/api/admin/orders/9
Accept:application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Get orders
POST https://localhost:8080/brokage/api/admin/orders/9/match
Accept:application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### POST Order
POST https://localhost:8080/brokage/api/admin/orders/
Accept:application/json
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "name": "{{$random.alphanumeric(15)}}"
}
> {% client.global.set("new_order_id", response.body.id); %}

### POST Order validation test
POST https://localhost:8080/brokage/api/admin/orders/
Accept:application/json
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "customerId": 1,
  "assetName": "USDTRY",
  "side": "BUY",
  "size": 2,
  "price": 500000.00
}

### Get orders
GET https://localhost:8080/brokage/api/admin/orders/1
Accept:application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Delete Order
DELETE https://localhost:8080/brokage/api/admin/orders/2
Accept:application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=