### Deposit to Customer Account
POST https://localhost:8080/brokage/api/admin/customers/1/deposit
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "amount": 500000.00
}

### Withdraw from Customer Account
POST https://localhost:8080/brokage/api/admin/customers/1/withdraw
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "amount": 5000.00
}

### List Customer Assets
GET https://localhost:8080/brokage/api/admin/assets?customerId=1
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
